
package com.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestInterfaceImplService", targetNamespace = "http://interfaces.example/", wsdlLocation = "http://localhost:8081/TestService?wsdl")
public class TestInterfaceImplService
    extends Service
{

    private final static URL TESTINTERFACEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTINTERFACEIMPLSERVICE_EXCEPTION;
    private final static QName TESTINTERFACEIMPLSERVICE_QNAME = new QName("http://interfaces.example/", "TestInterfaceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/TestService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTINTERFACEIMPLSERVICE_WSDL_LOCATION = url;
        TESTINTERFACEIMPLSERVICE_EXCEPTION = e;
    }

    public TestInterfaceImplService() {
        super(__getWsdlLocation(), TESTINTERFACEIMPLSERVICE_QNAME);
    }

    public TestInterfaceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTINTERFACEIMPLSERVICE_QNAME, features);
    }

    public TestInterfaceImplService(URL wsdlLocation) {
        super(wsdlLocation, TESTINTERFACEIMPLSERVICE_QNAME);
    }

    public TestInterfaceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTINTERFACEIMPLSERVICE_QNAME, features);
    }

    public TestInterfaceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestInterfaceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestInterfaceImpl
     */
    @WebEndpoint(name = "TestInterfaceImplPort")
    public TestInterfaceImpl getTestInterfaceImplPort() {
        return super.getPort(new QName("http://interfaces.example/", "TestInterfaceImplPort"), TestInterfaceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestInterfaceImpl
     */
    @WebEndpoint(name = "TestInterfaceImplPort")
    public TestInterfaceImpl getTestInterfaceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://interfaces.example/", "TestInterfaceImplPort"), TestInterfaceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTINTERFACEIMPLSERVICE_EXCEPTION!= null) {
            throw TESTINTERFACEIMPLSERVICE_EXCEPTION;
        }
        return TESTINTERFACEIMPLSERVICE_WSDL_LOCATION;
    }

}
